package com.example.blap.ui.screens.events

import com.example.blap.event.EventCreateRequest

data class EventActions(
    val onBeginCreate: () -> Unit,
    val onBeginEdit: () -> Unit,
    val onCreate: (EventCreateRequest) -> Unit,
    val onOpen: (String) -> Unit,
    val onUpdate: (EventCreateRequest) -> Unit,
    val onDeleteEvent: () -> Unit,
    val onJoin: () -> Unit,
    val onInvite: (String) -> Unit,
    val onSearchParticipant: (String) -> Unit,
    val onAcceptInvitation: (String) -> Unit,
    val onDeclineInvitation: (String) -> Unit,
    val onRevokeInvitation: (String) -> Unit,
    val onLeave: () -> Unit,
    val onPromoteMember: (String) -> Unit,
    val onRemoveMember: (String) -> Unit,
    val onDeleteLocalData: () -> Unit,
    val onShowAnnouncements: () -> Unit,
    val onPublishAnnouncement: (String) -> Unit,
    val onShowDiscussion: () -> Unit,
    val onLoadMoreDiscussion: () -> Unit,
    val onOpenDiscussionThread: (String) -> Unit,
    val onCreateDiscussionComment: (String, String?) -> Unit,
    val onToggleDiscussionLike: (String) -> Unit,
    val onDeleteDiscussionComment: (String) -> Unit,
    val onRequestGpsEntry: () -> Unit,
    val onRequestAdminAccess: () -> Unit,
    val onApproveAdminAccess: (String) -> Unit,
    val onScanCheckInQr: () -> Unit,
    val onShowCheckInQr: () -> Unit,
    val onHideCheckInQr: () -> Unit,
    val onShowSavedChat: () -> Unit,
    val onSendChat: (String) -> Unit,
    val onBack: () -> Unit,
)
